
server:
  port: 8101
spring:
  application:
    name: Shop API Gateway

  cloud:
    gateway:
#      routes:
#        - id: productService
#          uri: http://localhost:8102/
#          predicates:
#            - Path=/api/v1/products/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka
    instance.preferIpAddress: true
