
server:
  port: 8102
  error:
    include-message: always
spring:
  application:
    name: Product-Service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tayyab##123
    url: jdbc:mysql://localhost:3306/shopdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka
    instance.preferIpAddress: true