
server:
  port: 8101
spring:
  application:
    name: Product Service

#  server.port=8101
#
#  spring.application.name=Product Service
#
#  eureka.client.serviceUrl.defaultZone  = http://localhost:8100/eureka
#  eureka.client.instance.preferIpAddress = true
#
#
#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/shopdb
#  spring.datasource.username=root
#  spring.datasource.password=
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tayyab##123
    url: jdbc:mysql://localhost:3306/shopdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka
    instance.preferIpAddress: true